### ISSUE TITLE
Laravel?

### ISSUE THREAD

**Issue by Meverhart** [andi2garcia/OnLoL-Riot-API#10]
How would I go about using this with Laravel or another PHP framework?

**Comment by SeaRoth** [comment]
You're kidding, right?

![image](https://cloud.githubusercontent.com/assets/3461713/22832958/e4f937da-ef64-11e6-8212-c4e36dae7114.png)

**Comment by Meverhart** [comment]
Thanks.  I'm new to Laravel and PHP.
