### ISSUE TITLE
Most recent solo/duo games don't seem to be returned form $api -> matchHistory

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#11]
**Description:** 
match history does not return most recent games from solo/duo

**Steps to reproduce:**
1. $api->matchHistory("21419450","na");
2. View output

**Result:**
![image](https://cloud.githubusercontent.com/assets/3461713/25560151/ecced53a-2d00-11e7-84f3-787b7ca0763a.png)

**Expected Result:**
![image](https://cloud.githubusercontent.com/assets/3461713/25560140/a28c4872-2d00-11e7-9f1a-e9c8ca37a4b0.png)

- Latest game timestamp (at this moment) should be: 1493504238226 and not 1493440148627

**Comment by SeaRoth** [comment]
Only reason I figured this out is because I played with him for our last game and the timestamps weren't matching up (1 hour ago vs 19 hours ago)

![image](https://cloud.githubusercontent.com/assets/3461713/25560201/46ed72be-2d02-11e7-9729-85fc5add3d35.png)

**Comment by SeaRoth** [comment]
Looks like matchlist being deprecated

![image](https://cloud.githubusercontent.com/assets/3461713/25565821/bfe337b8-2d83-11e7-80e4-043167484dee.png)

and match v2.2

![image](https://cloud.githubusercontent.com/assets/3461713/25565829/e0f8e81c-2d83-11e7-984b-a7c51c87201b.png)

**Comment by d3sd1** [comment]
It was just about to update the constant.
Thank you for notifying. Solved!
