### ISSUE TITLE
ACCESS DENIED / 403 forbidden

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#14]
# Description:

- Receive error when accessing summonerByName

# Steps to reproduce:

1. $api->summonerByName("dyrus","na");
2. Access Denied

# Result:
![image](https://cloud.githubusercontent.com/assets/3461713/25584724/092efb78-2e4c-11e7-8538-23cea84d2e0f.png)

# Expected Result:
![image](https://cloud.githubusercontent.com/assets/3461713/25584889/b7947eb8-2e4c-11e7-9c3a-cf407b9ca678.png)

**Comment by d3sd1** [comment]
fixed!
