### ISSUE TITLE
$api-> recentGames(summonerId,region) is missing deaths

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#2]
Good morning,

I think recentGames is missing the statistic "deaths" inside the objet "stats".

Can anyone confirm or deny?

Thank you for sharing OnLoL-Riot-API.

**Comment by d3sd1** [comment]
Dear SeaRoth,
deaths aren't presented with that name, they're:
**numDeaths**
You can also check it out there:
https://developer.riotgames.com/api/methods#!/1078/3718

Screen:
http://prntscr.com/clhbrj

Regards :)
