### ISSUE TITLE
Static Data with Items

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#3]
When using the method staticData with "items" the json output is different than other methods such as recentGames.
## Example staticData()

$api->staticData("item/3142");
[ Picture](http://i.imgur.com/6sluAaH.png)

$api->staticData("item");
[Picture](http://i.imgur.com/DZ8detA.png)
## Example recentGames()

$api->recentGames('20844500', "na");
[Picture](http://i.imgur.com/0rIbq0Q.png)

Can anyone else confirm or deny?

**Comment by d3sd1** [comment]
Hi there.
On recentgames(), you can access ONLY THE SEARCHED SUMMONER ITEMS, by going to $recentgames['stats']['item0']
$recentgames['stats']['item1']
[...]
$recentgames['stats']['item6']
So there you will get the item ID, and with this item ID you can search the full content of the item by going:
$api->staticData("item/{ITEM_ID}");
It has a different output for saving some bytes, you know :P

**Comment by SeaRoth** [comment]
I was getting confused because of the JSON viewer extension on my chrome, thank you for answering! =) <3
