### ISSUE TITLE
Default Region

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#7]
**The update works flawlessly.**  
I really like the log files!  I can now see which API calls I'm making because Riot's API Dashboard is lacking in options.

# Only thing I would change is (if appropriate):
![image](https://cloud.githubusercontent.com/assets/3461713/21226536/c0af448e-c28a-11e6-8153-ee42259e0612.png)
Because I was calling EUW (not sure if this even matters)
![image](https://cloud.githubusercontent.com/assets/3461713/21227025/0021f29a-c28d-11e6-8c17-8bc0fdc9aaa2.png)

I tried making changes to riot.php so I could contribute but I failed.
## Things I tried:
![image](https://cloud.githubusercontent.com/assets/3461713/21226881/604db98e-c28c-11e6-8c0b-65b1e7a403c3.png)
![image](https://cloud.githubusercontent.com/assets/3461713/21226893/740b4202-c28c-11e6-97ce-c1e50b278ac2.png)
but I'm a boosted bonobo and it didn't work obviously (haha).

**Comment by d3sd1** [comment]
You should set up default region on config.conf, try it and if it persists I'll take a look :P

**Comment by d3sd1** [comment]
Oh lol understood so bad.
Im changing it, but it doesn't matters, since static data it's the same on all regions ;P

PD: Working on a really heavy update, it will have a new feature that you will really like it, it will be V2, and should be avaliable tomorrow or less than a week.

**Comment by SeaRoth** [comment]
I set up the default region in config.conf since the beginning. :)

![image](https://cloud.githubusercontent.com/assets/3461713/21229060/2276893e-c295-11e6-90fd-ce9a606ae927.png)

# 1st Test:
-Function parameter $region to 'euw'
![image](https://cloud.githubusercontent.com/assets/3461713/21229210/a1c071f0-c295-11e6-83ee-43a6a7d0b8c5.png)

and euw shows up in the log files:
![image](https://cloud.githubusercontent.com/assets/3461713/21229265/e2afce7c-c295-11e6-9128-c293d1d01989.png)

# 2nd Test:
-Function parameter $region to 'na'
![image](https://cloud.githubusercontent.com/assets/3461713/21229440/72d4b04e-c296-11e6-9144-8d2ab5b34628.png)

and na shows up in the log files:
![image](https://cloud.githubusercontent.com/assets/3461713/21229466/892d8a64-c296-11e6-8cc4-a7783bc57992.png)

# Notes:
- I'm not sure if this actually makes a big deal or not (we can close if it doesn't)

**Comment by d3sd1** [comment]
Yeye, just worked on solve it, like this:
![image](http://image.prntscr.com/image/672d3c4641244ce894113f61589812fc.png)
![image](http://image.prntscr.com/image/7d8c59e9004d427393f119bd0c814820.png)
As a spoiler, right now I'm working on stats. Feel free to tell me some stats that you would like to have.
Per example, summoners per region (%) and number.

**Comment by SeaRoth** [comment]
# Is this what you're talking about? (Summoners per region (%) and number:
![image](https://cloud.githubusercontent.com/assets/3461713/21273984/e511b78a-c37a-11e6-9f46-b24e265b7d0e.png)

**Comment by d3sd1** [comment]
That's a ladder, but I will add too :)

**Comment by d3sd1** [comment]
Will add on next patch! =)
