### ISSUE TITLE
Unknown Region and API calls

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#8]
## Description: 
- Endless loop of API calls results after sending incorrect region value to OnLoL-Riot-API

## Steps to Reproduce:
1. Use **an undefined variable** or **"         na  "** (with spaces) as the region when calling a function (e.g. summonerByName) with OnLoL-Riot-API
2. Look at the log files

## Results: 
1. Lots of API calls to unknown endpoints (see images below)

## Expected Results:
1. Return an error
2. Don't do anything

## Notes:
- Thank you for adding the log files to this project, they are very useful
- Trimming the $region value and then comparing it to the pre-defined list of regions (na, euw, etc...) sounds like the optimal solution

# Images:
![image](https://cloud.githubusercontent.com/assets/3461713/21273390/3f608f0c-c378-11e6-8fbf-0213bac104f6.png)

![image](https://cloud.githubusercontent.com/assets/3461713/21273454/873fda9e-c378-11e6-8608-7c80ca666423.png)

**Comment by d3sd1** [comment]
It retrieves NaN, so I assume that you deleted "na" on riot.api.regions, since it's an array which needs the regions where your api works.
Can you give me the request you're making and config.conf (without api key and mysql con)?

**Comment by d3sd1** [comment]
Solved on next patch, I just realised I made something with it lol. Repost this on trying next patch, it will be avaliable today almost for sure.

**Comment by d3sd1** [comment]
Added a subversion 1.4, with too many new features and some stats coded.
Would like to add you on skype (if you like) to talk something about this patches, and give an instant feedback.
Check it out asap! :P

**Comment by d3sd1** [comment]
My skype is **andiganja** btw

**Comment by SeaRoth** [comment]
added
