### ISSUE TITLE
Error on $api->currentGame when not in game

### ISSUE THREAD

**Issue by SeaRoth** [andi2garcia/OnLoL-Riot-API#9]
# Description:
- $api->currentGame is returning an error when the user is not in-game
- This error is different behavior than previous versions of OnLol-Riot-API
- The error bypasses my try catch and returns non-json data to my ajax callback

# Steps to reproduce:
1. Check currentGame with anyone (not in game)
2. Get error

# Results:
- The function errors out and returns data to ajax callback by itself
- The data sent back is not json either, per the console.log below
![image](https://cloud.githubusercontent.com/assets/3461713/21284038/35aef6e6-c3c4-11e6-9549-8be8bee208d5.png)

# Expected Results:
- Whatever the previous versions returned

# Notes: 
- If this is the new behavior of currentGame then I will adapt.  However, the functionality of this method has changed and it is returning different data than before.  It's erroring out before having a chance to do anything with it.

# Images:
error.log:
![image](https://cloud.githubusercontent.com/assets/3461713/21284010/7ed4a98e-c3c3-11e6-8674-d88e8791592b.png)

Regular Log File:
![image](https://cloud.githubusercontent.com/assets/3461713/21284094/56335fb8-c3c6-11e6-9dab-fe0790a1334d.png)

**Comment by SeaRoth** [comment]
The main problem I am seeing is $api->currentGame is returning the URL && API key just used.

## (callback.php) Calling $api->currentGame
![image](https://cloud.githubusercontent.com/assets/3461713/21294565/6977b248-c4f4-11e6-911f-50e79ef16187.png)

- There should be no output from this function because I commented out both printJson function calls
- $api->currentGame is returning the API call it just made, API key included 
- The error inside $api->currentGame is crashing (I think?)

## (index.php) ajax function that checks for success && json
![image](https://cloud.githubusercontent.com/assets/3461713/21294555/33b1d6d4-c4f4-11e6-872b-1ee7cf771e0e.png)
- I added the search for "NOT_FOUND" since running into this problem

## Console.log value from the above ^^ try / catch
![image](https://cloud.githubusercontent.com/assets/3461713/21294594/4083567a-c4f5-11e6-8f18-d654c832bc4c.png)

**Comment by SeaRoth** [comment]
Same thing happens for **league** && **stats**

![image](https://cloud.githubusercontent.com/assets/3461713/21294729/c8ed909a-c4f8-11e6-9be8-1a526defd31d.png)

**Comment by d3sd1** [comment]
I'm taking a look. Will upload patch tomorrow.
Thank you for notifying!

**Comment by d3sd1** [comment]
Just solved it 📦 
Will upload patch later, if I dont wait for stats code.
